import { writeFile } from 'node:fs/promises';
import { getBooks } from './download.js';
import { extract } from './extract.js';
import { buildGraph } from './graph.js';
import { analyze } from './analyze.js';

async function main() {
  console.log('Potter Graph — building\n');

  console.log('1/4  fetching books');
  const books = await getBooks();

  console.log('2/4  extracting entities & relations');
  const corpus = extract(books);

  console.log('3/4  building graph & metrics');
  const graph = buildGraph(corpus);

  console.log('4/4  analysing & exporting');
  const data = analyze(graph, corpus);

  const banner = '// Generated by `npm run build`. Do not edit by hand.\n';
  await writeFile('report/data.js', `${banner}window.DATA = ${JSON.stringify(data)};\n`, 'utf8');

  // --- console summary, doubles as a sanity check on extraction quality ---
  const attribPct = ((corpus.quotesAttributed / corpus.quotesSeen) * 100).toFixed(1);
  console.log('\n────────────────────────────────────────');
  console.log(`nodes: ${data.meta.nodeCount}   edges: ${data.meta.edgeCount}   mentions: ${data.meta.totalMentions}`);
  console.log(`dialogue: ${corpus.quotesAttributed}/${corpus.quotesSeen} quotes attributed (${attribPct}%)`);
  console.log('\ntop 5 by mentions:');
  [...corpus.entities.values()]
    .filter((e) => e.type === 'character')
    .sort((a, b) => b.mentions - a.mentions)
    .slice(0, 5)
    .forEach((e) => console.log(`  ${e.label.padEnd(20)} ${e.mentions}`));

  console.log('\ncommunities:', new Set(data.nodes.map((n) => n.community)).size);

  // recall probe: frequent capitalized tokens we never modelled
  console.log('\ntop unknown capitalized tokens (gazetteer gaps):');
  [...corpus.unknownCapitalized.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 12)
    .forEach(([tok, n]) => console.log(`  ${tok.padEnd(20)} ${n}`));

  console.log('\nwrote report/data.js — open report/index.html to view.');
}

main().catch((err) => {
  console.error('\nbuild failed:', err.message);
  process.exit(1);
});
