import type { GazetteerEntry } from './types.js';

// Hand-curated vocabulary for books 1-4. A closed list keeps precision high; the
// price is recall (see DESIGN.md). Aliases are matched case-sensitively against the
// original text, so common-word surnames like "Black", "Wood" or "Fang" don't leak
// in from lowercase prose. Order inside `aliases` doesn't matter - the matcher sorts
// by length so "Professor McGonagall" wins over "McGonagall".

const characters: [string, string[]][] = [
  ['Harry Potter', ['Harry Potter', 'Harry', 'Mr. Potter']],
  ['Ron Weasley', ['Ron Weasley', 'Ronald Weasley', 'Ronald', 'Ron']],
  ['Hermione Granger', ['Hermione Granger', 'Hermione', 'Miss Granger']],
  ['Albus Dumbledore', ['Professor Dumbledore', 'Albus Dumbledore', 'Dumbledore']],
  ['Rubeus Hagrid', ['Rubeus Hagrid', 'Hagrid']],
  ['Severus Snape', ['Professor Snape', 'Severus Snape', 'Snape']],
  ['Draco Malfoy', ['Draco Malfoy', 'Draco']],
  ['Lord Voldemort', ['Lord Voldemort', 'Voldemort', 'You-Know-Who', 'He-Who-Must-Not-Be-Named', 'Tom Riddle', 'Tom Marvolo Riddle']],
  ['Minerva McGonagall', ['Professor McGonagall', 'Minerva McGonagall', 'McGonagall']],
  ['Neville Longbottom', ['Neville Longbottom', 'Neville']],
  ['Ginny Weasley', ['Ginny Weasley', 'Ginny']],
  ['Fred Weasley', ['Fred Weasley', 'Fred']],
  ['George Weasley', ['George Weasley', 'George']],
  ['Percy Weasley', ['Percy Weasley', 'Percy']],
  ['Molly Weasley', ['Mrs. Weasley', 'Molly Weasley', 'Molly']],
  ['Arthur Weasley', ['Mr. Weasley', 'Arthur Weasley']],
  ['Bill Weasley', ['Bill Weasley', 'Bill']],
  ['Charlie Weasley', ['Charlie Weasley', 'Charlie']],
  ['Sirius Black', ['Sirius Black', 'Sirius']],
  ['Remus Lupin', ['Professor Lupin', 'Remus Lupin', 'Lupin']],
  ['Peter Pettigrew', ['Peter Pettigrew', 'Pettigrew', 'Wormtail']],
  ['Cornelius Fudge', ['Cornelius Fudge', 'Minister Fudge', 'Fudge']],
  ['Dobby', ['Dobby']],
  ['Winky', ['Winky']],
  ['Cedric Diggory', ['Cedric Diggory', 'Cedric', 'Diggory']],
  ['Cho Chang', ['Cho Chang', 'Cho']],
  ['Fleur Delacour', ['Fleur Delacour', 'Fleur']],
  ['Viktor Krum', ['Viktor Krum', 'Viktor', 'Krum']],
  ['Alastor Moody', ['Professor Moody', 'Mad-Eye Moody', 'Alastor Moody', 'Mad-Eye', 'Moody']],
  ['Gilderoy Lockhart', ['Professor Lockhart', 'Gilderoy Lockhart', 'Lockhart']],
  ['Quirinus Quirrell', ['Professor Quirrell', 'Quirinus Quirrell', 'Quirrell']],
  ['Vernon Dursley', ['Uncle Vernon', 'Mr. Dursley', 'Vernon Dursley', 'Vernon']],
  ['Petunia Dursley', ['Aunt Petunia', 'Mrs. Dursley', 'Petunia']],
  ['Dudley Dursley', ['Dudley Dursley', 'Dudley']],
  ['Argus Filch', ['Argus Filch', 'Filch']],
  ['Oliver Wood', ['Oliver Wood']],
  ['Lucius Malfoy', ['Lucius Malfoy', 'Lucius']],
  ['Bartemius Crouch', ['Bartemius Crouch', 'Barty Crouch', 'Mr. Crouch']],
  ['Ludo Bagman', ['Ludo Bagman', 'Bagman']],
  ['Rita Skeeter', ['Rita Skeeter', 'Rita', 'Skeeter']],
  ['Moaning Myrtle', ['Moaning Myrtle', 'Myrtle']],
  ['James Potter', ['James Potter']],
  ['Lily Potter', ['Lily Potter', 'Lily']],
  ['Pomona Sprout', ['Professor Sprout', 'Madam Sprout', 'Sprout']],
  ['Filius Flitwick', ['Professor Flitwick', 'Flitwick']],
  ['Sybill Trelawney', ['Professor Trelawney', 'Sybill Trelawney', 'Trelawney']],
  ['Poppy Pomfrey', ['Madam Pomfrey', 'Pomfrey']],
  ['Rolanda Hooch', ['Madam Hooch', 'Hooch']],
  ['Seamus Finnigan', ['Seamus Finnigan', 'Seamus']],
  ['Dean Thomas', ['Dean Thomas']],
  ['Lavender Brown', ['Lavender Brown', 'Lavender']],
  ['Parvati Patil', ['Parvati Patil', 'Parvati']],
  ['Colin Creevey', ['Colin Creevey', 'Colin']],
  ['Angelina Johnson', ['Angelina Johnson', 'Angelina']],
  ['Lee Jordan', ['Lee Jordan']],
  ['Marcus Flint', ['Marcus Flint']],
  ['Griphook', ['Griphook']],
  ['Firenze', ['Firenze']],
  ['Nearly Headless Nick', ['Nearly Headless Nick', 'Sir Nicholas']],
  ['Peeves', ['Peeves']],
  ['Aunt Marge', ['Aunt Marge', 'Marge']],
  ['Igor Karkaroff', ['Igor Karkaroff', 'Karkaroff']],
  ['Madame Maxime', ['Madame Maxime', 'Madame Olympe Maxime']],
];

const spells: [string, string[]][] = [
  ['Wingardium Leviosa', ['Wingardium Leviosa']],
  ['Expelliarmus', ['Expelliarmus']],
  ['Alohomora', ['Alohomora']],
  ['Expecto Patronum', ['Expecto Patronum']],
  ['Avada Kedavra', ['Avada Kedavra']],
  ['Crucio', ['Crucio', 'Cruciatus Curse']],
  ['Imperio', ['Imperio', 'Imperius Curse']],
  ['Lumos', ['Lumos']],
  ['Nox', ['Nox']],
  ['Accio', ['Accio']],
  ['Petrificus Totalus', ['Petrificus Totalus']],
  ['Rictusempra', ['Rictusempra']],
  ['Riddikulus', ['Riddikulus']],
  ['Locomotor Mortis', ['Locomotor Mortis']],
  ['Densaugeo', ['Densaugeo']],
  ['Furnunculus', ['Furnunculus']],
  ['Serpensortia', ['Serpensortia']],
  ['Tarantallegra', ['Tarantallegra']],
  ['Finite Incantatem', ['Finite Incantatem', 'Finite']],
  ['Sonorus', ['Sonorus']],
  ['Quietus', ['Quietus']],
  ['Obliviate', ['Obliviate']],
  ['Reparo', ['Reparo']],
  ['Diffindo', ['Diffindo']],
  ['Engorgio', ['Engorgio']],
  ['Reducto', ['Reducto']],
  ['Impedimenta', ['Impedimenta']],
  ['Stupefy', ['Stupefy']],
  ['Enervate', ['Enervate', 'Ennervate']],
  ['Morsmordre', ['Morsmordre']],
  ['Priori Incantatem', ['Priori Incantatem']],
  ['Waddiwasi', ['Waddiwasi']],
  ['Mobiliarbus', ['Mobiliarbus']],
  ['Mobilicorpus', ['Mobilicorpus']],
  ['Aparecium', ['Aparecium']],
  ['Point Me', ['Point Me']],
];

const places: [string, string[]][] = [
  ['Hogwarts', ['Hogwarts']],
  ['Gryffindor Tower', ['Gryffindor Tower']],
  ['Great Hall', ['Great Hall']],
  ['Diagon Alley', ['Diagon Alley']],
  ['Knockturn Alley', ['Knockturn Alley']],
  ['Hogsmeade', ['Hogsmeade']],
  ['Privet Drive', ['Privet Drive', 'number four']],
  ['The Burrow', ['the Burrow']],
  ['Forbidden Forest', ['Forbidden Forest', 'Dark Forest']],
  ['Gringotts', ['Gringotts']],
  ['Ministry of Magic', ['Ministry of Magic']],
  ['Azkaban', ['Azkaban']],
  ["King's Cross", ["King's Cross"]],
  ['Platform Nine and Three-Quarters', ['Platform Nine and Three-Quarters', 'platform nine and three-quarters']],
  ['Hospital Wing', ['hospital wing']],
  ['Chamber of Secrets', ['Chamber of Secrets']],
  ['Shrieking Shack', ['Shrieking Shack']],
  ['Leaky Cauldron', ['Leaky Cauldron']],
  ["Ollivanders", ["Ollivanders"]],
  ['Honeydukes', ['Honeydukes']],
  ['Three Broomsticks', ['Three Broomsticks']],
  ['Beauxbatons', ['Beauxbatons']],
  ['Durmstrang', ['Durmstrang']],
  ['Little Whinging', ['Little Whinging']],
  ['Owlery', ['Owlery', 'owlery']],
];

const creatures: [string, string[]][] = [
  // named beasts
  ['Fawkes', ['Fawkes']],
  ['Hedwig', ['Hedwig']],
  ['Crookshanks', ['Crookshanks']],
  ['Scabbers', ['Scabbers']],
  ['Buckbeak', ['Buckbeak']],
  ['Aragog', ['Aragog']],
  ['Norbert', ['Norbert']],
  ['Fluffy', ['Fluffy']],
  ['Fang', ['Fang']],
  ['Errol', ['Errol']],
  ['Nagini', ['Nagini']],
  ['Pigwidgeon', ['Pigwidgeon']],
  ['Hermes', ['Hermes']],
  // species
  ['Dementor', ['Dementor', 'dementors', 'dementor']],
  ['Boggart', ['Boggart', 'boggart']],
  ['Hippogriff', ['Hippogriff', 'hippogriff']],
  ['Basilisk', ['Basilisk', 'basilisk']],
  ['Troll', ['troll']],
  ['Dragon', ['dragon']],
  ['Werewolf', ['werewolf']],
  ['Centaur', ['centaur']],
  ['Acromantula', ['Acromantula', 'acromantula']],
  ['Grindylow', ['grindylow']],
  ['Phoenix', ['phoenix']],
  ['Unicorn', ['unicorn']],
  ['House-elf', ['house-elf', 'house elf']],
  ['Goblin', ['goblin']],
  ['Veela', ['veela']],
  ['Blast-Ended Skrewt', ['Blast-Ended Skrewt', 'skrewt']],
  ['Niffler', ['niffler']],
  ['Mandrake', ['Mandrake', 'mandrake']],
  ['Cornish Pixie', ['Cornish pixie', 'Cornish pixies']],
];

const houses: [string, string[]][] = [
  ['Gryffindor', ['Gryffindor']],
  ['Slytherin', ['Slytherin']],
  ['Hufflepuff', ['Hufflepuff']],
  ['Ravenclaw', ['Ravenclaw']],
];

function build(pairs: [string, string[]][], type: GazetteerEntry['type']): GazetteerEntry[] {
  return pairs.map(([canonical, aliases]) => ({ canonical, type, aliases }));
}

export const GAZETTEER: GazetteerEntry[] = [
  ...build(characters, 'character'),
  ...build(spells, 'spell'),
  ...build(places, 'place'),
  ...build(creatures, 'creature'),
  ...build(houses, 'house'),
];

export function slug(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}
